// FILE: pubspec.yaml
name: rhineix_mkey_app
description: "An inventory management app for MKey workshop."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Required for RTL support
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0

  # Networking
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  cached_network_image: ^3.3.1

  # UI & Theming
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  material_symbols_icons: ^4.2727.0
  flutter_staggered_animations: ^1.1.1

  # Utility
  intl: ^0.20.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  image_cropper: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false # CHANGED: Set to false to skip iOS icon generation
  remove_alpha_ios: true # ADDED: Good practice to remove transparency for iOS
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F4F7F9"
  color_dark: "#121212"
  image: assets/icon.png
  android_12:
    color: "#F4F7F9"
    color_dark: "#121212"
    image: assets/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/