name: rhineix_mkey_app
description: "An inventory management app for MKey workshop."
publish_to: 'none'
version: 2.1.0+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Firebase Backend
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.2 # New package for notifications

  # Local Storage & Path
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  path: ^1.9.0

  # Networking & Caching
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2

  # UI & Theming
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  material_symbols_icons: ^4.2727.0
  flutter_staggered_animations: ^1.1.1
  marquee: ^2.2.3

  # Utility
  intl: ^0.20.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  image_cropper: ^7.0.0
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  
  # Backup & Restore
  archive: ^3.5.1
  file_picker: ^8.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F4F7F9"
  color_dark: "#121212"
  image: assets/icon.png
  android_12:
    color: "#F4F7F9"
    color_dark: "#121212"
    image: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/