name: Build Flutter APK (arm64)

on:
  workflow_dispatch:   # يدوي فقط

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.35.2   # نفس النسخة عندك محلياً

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze || true

      - name: Run tests
        run: flutter test || true

      - name: Build release APK (arm64 only)
        run: flutter build apk --release --target-platform=android-arm64

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: build/app/outputs/flutter-apk/app-release.apk
